PC = POLYCHAOS(1,4);
[A,x] = random(PC,10);
y = x.^2;
s = LeastSquaresSolver('regularization',false,...
    'regularizationType','l1',...
    'modelSelection',true,...
    'errorEstimation',true,...
    'errorEstimationType','kfold',...
    'errorEstimationOptions',struct('correction',false),...
    'basisAdaptation',false,...
    'basisAdaptationPath',[]);
[sol,output] = solve(s,y,A);
[u,err] = solve_leastsquares(A,y','',[],'kfold');
sol
u'
output.relativeError
err